### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by Andrea-MariaDB-2** [opencollective/documentation-old#124]

**Comment by SudharakaP** [comment]
This ticket is closed due to **guidelines not followed**. 

All tickets should follow the guidelines as mentioned in: 

- The [Code of Conduct](https://github.com/opencollective/opencollective/blob/main/CODE_OF_CONDUCT.md).

- Submission guidelines as mentioned in our [README file](https://github.com/opencollective/opencollective/blob/main/README.md#issues).
