### ISSUE TITLE
FAQ: Financial Contributors

### ISSUE THREAD

**Issue by contraexemplo** [opencollective/documentation-old#38]
Currently, our docs have two FAQs under the (deprecated) section "Backers and Sponsors":
- https://docs.opencollective.com/help/backers-and-sponsors (which seems to be more focused on individual contributors)
- https://docs.opencollective.com/help/backers-and-sponsors/sponsor-faq (which is focused on organizations)

1. Should we create different pages and subpages for individuals and organizations? A lot of info from that section is specific for organizations.
2. How should we call contributions from organizations? Sponsorship?

**Comment by contraexemplo** [comment]
Pinging @alanna and @jaskirat2000

**Comment by alanna** [comment]
Discussed with @contraexemplo today - we decided to keep both individuals and organizations under one section called Financial Contributors. They will add an intro section explaining the different kinds of financial contributors and move the FAQs into those subsections.

The terms are "individual financial contributors" and "organizational financial contributors" - these are way too long and clumsy but we haven't found better ones. We don't want to use "Backers" and "Sponsors" anymore because we found it caused too much confusion as different groups have different definitions for those words.
